### ISSUE TITLE
[Data] Shadowlands Data Entry

### ISSUE THREAD

**Issue by dashnine** [dashnine/PaperBlossoms#13]
Includes typical schools/families/eq, as well as Patterns, Scrolls, and a new Heritage.

**Comment by meow9th** [comment]
High priority
- [ ] New samurai heritages
- [ ] Item patterns (new entity), including associated techniques
- [ ] Signature scrolls (appended to personal effects), including associated techniques

Next priority
- [ ] New advantages/disadvantages
- [ ] New techniques, including Mahō
- [ ] New clans
- [ ] New weapons
- [ ] New armor
- [ ] New personal effects
- [ ] New items (artifacts of Jigoku and blessed treasures)
- [ ] New schools
- [ ] New titles
