### ISSUE TITLE
Linux implementation for PaperBlossoms

### ISSUE THREAD

**Issue by orestisfra** [dashnine/PaperBlossoms#137]
I don't know if that's where I need to report that but I can't find any other link for that stuff (discord/email).
I tried compiling the source code on linux and I am completely unable to.
**What I tried**: compiling main.cpp then mainwindow.cpp then all of them at the same time on src. compiling tst_testmain.cpp. opening QtCreator and try compiling from there.
**The problem**: it gives a ton of errors such as QApplication QTranslator QDebug etc files don't exist, Qt Creator gives errors on almost all lines about undeclared identifiers and unknown type names
**The troubleshoot**: I use latest kde, so I have most qt5 packages for creating programs but there is no documentation/readme_file to refer to for this program, to check for dependences or general instructions or what I need to compile it.
**The request**: Is it possible for a make file to be created, to make it easy to compile/install the app on linux or at least get some instructions on how to run it/compile it?
I am not a very experienced programmer and I know very little about C++ but I am interested in this project. I may be able to help expand the wiki or write the doc for linux or even add a translation for my mother language if I figure out how to compile it.
thank you.

![Screenshot_20190711_123024](https://user-images.githubusercontent.com/25325630/61041831-b2890400-a3db-11e9-9326-1e979c62bfa6.png)
![Screenshot_20190711_123038](https://user-images.githubusercontent.com/25325630/61041832-b2890400-a3db-11e9-9b62-b8f88b966533.png)

**Comment by dashnine** [comment]
Orestisfra,

At a glance, that looks like your development environment can't find your Qt development libraries. That said, you're right--I don't have much documentation up to guide setting up a build on linux yet (we did a test Linux build about a month ago to confirm that it works, though).

Let me see if I can put together a step-by-step guide here in the next week or so! In the meanwhile, my best guess: if you used apt, try uninstalling that version, then downloading the official community edition installer from download.qt.io/official_releases and use it to install creator and the SDK. That installer sometimes does a better job of setting up the developer libraries in the right places than apt-get :) Basically try something like the guide here: https://www.ics.com/blog/getting-started-qt-and-qt-creator-linux

**Comment by dashnine** [comment]
For building, you should just be able to open the .Proj file and hit the Play button in the lower left :) It will run qmake and then build the files in order, if everything is working right!

**Comment by orestisfra** [comment]
I understand that this is an opensource early project so I am not demanding anything. Thank you for the response. I use an arch based distro so I downloaded the Qt5 packages from the repos or aur and are all installed on $PATH. I'll reinstall them if need be. I tried compiling the program on my home folder (/home/user/Templates/PaperBlossoms/).
Right now I opened PaperBlossoms.pro with QtCreator and hit run. It ran just fine. Not the most convenient way but oh well... It compiles with just a few warnings. :)

**Comment by orestisfra** [comment]
sorry for the double post but do I have to run the program that way everytime?

**Comment by dashnine** [comment]
Ah! Then you're up and running. Excellent!

If you want to run the application without going through Creator, you'll need to set up a deployment. On Linux, this can be kind of a pain - - commonly you'd set up a wrapper script that sets LD_LIBRARY_PATH to point to the correct Qt DLLs (I usually copy them into my application directory) , then runs the app. Qt has some documentation on this process at https://doc.qt.io/qt-5/Linuxdeployment.html. 

Alternatively, you could check out a tool that does that for you ; it looks like someone has set up a Linux deployment tool at https://github.com/probonopd/linuxdeployqt . I haven't tried it--your mileage may vary!

**Comment by dashnine** [comment]
https://github.com/dashnine/PaperBlossoms/wiki/Linux-Build-Guide -- Added a simple build guide for linux!
