### ISSUE TITLE
Topaz armor is missing from equipment

### ISSUE THREAD

**Issue by neonbasschild** [dashnine/PaperBlossoms#141]
Topaz Champaign armor is missing from the equipment section. It's from the starter box adventure.

**Comment by dashnine** [comment]
So, based on the fact that the specification for the armor is incomplete (some things like cost are missing, IIRC) I believe we settled on not including a pregenerated version of this.  However, the app *should* support creating a custom/modified armor in the game to represent the topaz armor for your character/game!
