### ISSUE TITLE
[WIN] Text size to large in equipment section (High DPI Scaling)

### ISSUE THREAD

**Issue by neonbasschild** [dashnine/PaperBlossoms#142]
I have a player reporting that the text size for the equipment section is so large its almost unuseable.

**Comment by dashnine** [comment]
I would *assume* this is window size -- the text size should be no different from the rest of the app, but I'll take a look. and see if there's anything funky there. Do you know what resolution the player is running at, @neonbasschild ?

**Comment by neonbasschild** [comment]
3840x2160 he does have two monitors and I don't know if that affects anything. He said he would get my screenshots later today.

**Comment by neonbasschild** [comment]
![Capture](https://user-images.githubusercontent.com/8492503/61841844-b8f79100-ae5b-11e9-8781-213a94cb4080.PNG)
![Capture3](https://user-images.githubusercontent.com/8492503/61841845-b8f79100-ae5b-11e9-84e1-60e8360355c2.PNG)
here is what is happening on his computer

**Comment by dashnine** [comment]
Holy mackerel, that's some wacky scaling.  So my best guess right now is that this has something to do with Qt's built-in High-DPI scaling. (https://doc.qt.io/archives/qt-5.6/highdpi.html) . My own display is 3440x1440, and doesn't behave this way -- so we'll see if I can even properly test it.  I'll try a couple things, and may reach out to you with a test build if I can't replicate the results here.

**Comment by dashnine** [comment]
Per response on the forums, closing this since it was resolved with settings on the target system.

If anyone else has this issue, you can check your scaling settings on the system, or try the following flags:

PaperBlossoms.exe -platform windows:dpiawareness=0
PaperBlossoms.exe -platform windows:dpiawareness=1
PaperBlossoms.exe -platform windows:dpiawareness=2

And see if those change your results!  For now though: closing.

**Comment by dashnine** [comment]
Additional note: Per @neonbasschild, the following resolved the issue locally:
Right click the executable and choose Properties.
Click the Compatibility tab->Change high DPI settings->Check 'Override high DPI scaling behavior' .

**Comment by neonbasschild** [comment]
Amazing I’ll pass it to my player.
