### ISSUE TITLE
Total Earned XP cannot exceed 99 points

### ISSUE THREAD

**Issue by JasonArentz-personal** [dashnine/PaperBlossoms#171]
The Total Earned field in the Advancement tab cannot exceed 99 xp. 
It looks to me like it is limited to 2 digits. Maybe 3 would suffice?

**Comment by dashnine** [comment]
Resolved by 468020ed63c4301c107a903c15376471533970bd

**Comment by Shiwo01** [comment]
I have the 1.2.2. and still stoped at 99.

**Comment by dashnine** [comment]
> I have the 1.2.2. and still stoped at 99.
> 
> update: just realised, 1.2.2 had been released in Sept, and issue "resolved" at December..
> 
> so I guess it will be on the next release..

Yes indeed -- there are a number of fixes that have been merged, but we haven't put together a release for a while.  I have a few things I want to get done before Path of Waves before I push!
