### ISSUE TITLE
Support Ronin/Gaijin 20 Questions

### ISSUE THREAD

**Issue by dashnine** [dashnine/PaperBlossoms#175]
1) Will require a selector at start of wizard.  
2) New Gaijin/Ronin Background/Upbringing tables
3) Changes to questions.  Visibility check on each wizard page load.
4) For family (/upbrininging): now support selecting schools

**Comment by meow9th** [comment]
All PoW data is in! Unless you find more data entry issues

**Comment by dashnine** [comment]
Resolved in #193
