### ISSUE TITLE
Agasha Mystic School 

### ISSUE THREAD

**Issue by yngtnrpdx** [dashnine/PaperBlossoms#186]
I think that the invocation Tempest of Air granted at character creation for this school should be Tetsubo of Earth. 
thank you all for the wonderful program.

**Comment by dashnine** [comment]
We actually have fixed that -- closing this as a duplicate of #181.  Resolved in commit: https://github.com/dashnine/PaperBlossoms/commit/c5211a813f37b4b68234bea47d8d67180a1a8bd9

You should see the fix whenever we next release! :-D

Thanks for the report!

**Comment by yngtnrpdx** [comment]
Now i see it, sorry first time using the site thank you for the reply.

**Comment by dashnine** [comment]
No problem at all!  Thanks for the report. :)
