### ISSUE TITLE
There is no way to edit equipment you already have.

### ISSUE THREAD

**Issue by Daeglan** [dashnine/PaperBlossoms#188]
For example if you have a pillow book in your gear. You have no way to add a description  to be Kakita's the sword.. or The Dao of Shinsei. for example. 
You cant add a pattern to a sword and so on

**Comment by dashnine** [comment]
Indeed. Current workaround is to add a new version of the weapon and remove the old.  This is a duplicate of #51 Support editing items, however.  Closing this as duplicate; to follow progress here, you can keep an eye on https://github.com/dashnine/PaperBlossoms/issues/51

:)  Thanks for the report!
