### ISSUE TITLE
[data] Support Deathly Turns

### ISSUE THREAD

**Issue by dashnine** [dashnine/PaperBlossoms#204]
https://images-cdn.fantasyflightgames.com/filer_public/de/4f/de4f1c2a-1640-4687-ac88-c3e1d817ec4f/l5r13dlc_deathlyturns_marketing_optimized.pdf

**Comment by meow9th** [comment]
Added. See 46ba196. 

Remember that Resplendent traveling clothes and Ceremonial yumi have made-up stats. See armor.json and weapons.json for details.

**Comment by dashnine** [comment]
closed with commit 46ba196a4a16ee6f9df0b55510c6303711cbebcf
