### ISSUE TITLE
Fix Secrets on the Wind for Soshi Illusionist school

### ISSUE THREAD

**Issue by dcfq** [dashnine/PaperBlossoms#209]
Soshi Illusionist learns their spells as a Fortunist school (page 80 on the sidebar), however when advancing a character, Secrets on the Wind doesn not appear as selectable invocation unless 'Remove All Restrictions' is marked.

**Comment by dashnine** [comment]
![image](https://user-images.githubusercontent.com/28985783/94092686-3efcc800-fdd0-11ea-8897-064c40d49c79.png)

So we only use the one name, for the data -- we don't support the alternative names, at this point.  That said, it looks like I can see that spell just fine on a soshi illusionist, once it hits rank 2?  Is this what you're seeing?

**Comment by dcfq** [comment]
Double checked here and it only appears when I mark Remove all Restrictions, will try to redownload and check if any file was missing or corrupted, will post my findings tomorrow.

**Comment by dashnine** [comment]
Cool! It is Rank 2, so be sure you've reached that. If you're going for a clean build, be sure it updates your db (you can close the app, delete the db from the data directory, and rerun to guarantee a clean db).

**Comment by dcfq** [comment]
I had rank 2 indeed, was able to reproduce it again today. However, it seems the 1.3.1 was using the database from the older version 1.2.2, so deleting and remaking it solved the issue, thanks
