### ISSUE TITLE
Application crashes on selecting "Special Training"

### ISSUE THREAD

**Issue by ZenTheMan01** [dashnine/PaperBlossoms#226]
When attempting to buy an upgrade at half cost via the Special Training option, attempting to tick that box causes my Paper Blossoms application to freeze for a few seconds and then crash immediately after. There appears to be one way to make it work normally; if I pick the Techniques option for what to spend experience on and select a specific technique, then try and tick Special Training, the application does not crash. It still won't crash at that point if I change to spending experience on a skill or ring. However, trying to untick Special Training after that while I have Skill or Ring selected instead of Technique it crashes again.

**Comment by dashnine** [comment]
Looks like I made some assumptions about indexes there. Should be a straightforward fix if I can shake out the cobwebs.  Thanks for the excellent report!
