### ISSUE TITLE
Ishiken school

### ISSUE THREAD

**Issue by ZenithDoom** [dashnine/PaperBlossoms#230]
I can't find the school of Ishiken on the version 1.4

it's in working progress?

**Comment by dashnine** [comment]
It's available on mine -- Samurai->Phoenix->Ishiken Initiate School.  If this is your first update for a while, mou might sitll have an old DB in place -- Try the following:
1) Tools->Open Applicacation Data Directory
2) Close the application
3) Delete or rename paperblossoms.db
4) relaunch paperblossoms.exe

Note that if you have any custom data or descriptions, you'll want to export it to save it beforehand. :)

**Comment by ZenithDoom** [comment]
Ok, i renamed the .db file, and relaunched paperblossom.

Now it work. Thanks.
