### ISSUE TITLE
Kuni Family skills

### ISSUE THREAD

**Issue by Derkaizer71** [dashnine/PaperBlossoms#40]
I just was looking at a character I built and noticed that the Kuni family skills seem to be Smithing and Labor Which are the Kaiu Family skills. THe Kuni family skills should be Medicine and Theology.

**Comment by dashnine** [comment]
Good catch!  We'll get that cleared in the next release.  Thanks for the report!

**Comment by Derkaizer71** [comment]
Your welcome. I might try creating up a character from each clan/family
since I'm not really able to see the database.

**Comment by dashnine** [comment]
That would be great testing--we're happy to fix anything you find! 

If you do want to look at the database, you can do so using DB Browser for SqlLite. The DB location can be seen by opening the app and choosing Tools->open application data directory... :)

But! Your current testing clearly worked very well :-D let us know if you find anything else!

**Comment by Derkaizer71** [comment]
I will do that
