### ISSUE TITLE
Limits on Skills and Rings

### ISSUE THREAD

**Issue by Skeranan** [dashnine/PaperBlossoms#81]
Hi, i saw a bug (probably just a miss)
Page 41 : 
> All characters begin with 1 rank in each ring and 0 ranks
> in each skill. You cannot raise a ring or skill above rank
> 3 during character creation. If a choice would result in a
> ring rising above rank 3 during character creation, then
> you must choose a different ring to increase instead,
> as long as that ring would also not be increased above
> rank 3.
> Similarly, if a choice would result in a skill rising
> above rank 3 during character creation, then you must
> choose a different skill that is not already at rank 3 to
> increase instead.

I can create a Shosuro Infiltrator with 4 in Air without any warning. 

PS : sorry for my bad english

**Comment by dashnine** [comment]
Thanks for the report! It should catch that at the end of the process and provide options to reassign rings and skills that exceed 3, on the same page as the "How should your character die?" Question. Did that happen with your build?

**Comment by Skeranan** [comment]
Ok, i see the remplacement page, this time. No idea of what happens last time, it works when i try to do again now :/

For my example : 
Scorpion > Shosuro (i chose Air) > Shosuro Infiltrator School (+1 Air too, so it causes a Air 4)

I tried again and the bug is not here now :o

**Comment by dashnine** [comment]
Heisenbug! :)

Cool cool. For now, I'll mark this as closed--could not duplicate. But!! If you can duplicate it, just reply here with steps and we'll get it reopened and chased down. :-) Thanks again!
